apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\williammolina\Documents\kompose.exe -f .\docker-compose.yml
      convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: demo
  name: demo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: demo
    spec:
      containers:
      - image: demo:1.0
        name: demo
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
