apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\williammolina\Documents\kompose.exe -f .\docker-compose.yml
      convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: demo
  name: demo
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: demo
status:
  loadBalancer: {}
